# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b93677f2d95e19c0aa312b29c4e2aaad65fe535df74d456f2b9b7e168ebffa3fa52b517b643b706d73da0dbfa8009d9c1ce8eb15911ff9a8cfc6730b475528b

test:
  secret_key_base: 879319dcce1d846e5d28928eeb2b64a4d2cf56f76f666c242f3fa77152b6984ac14928b98624bf0f3136f34815ce7184d817332e100a1f07461b1d2615fddf21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
